export const actionTypes = {
   ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
   REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
   SELECT_PERSON: "SELECT_PERSON",
   ADD_FILM: "ADD_FILM",
   LOG_OUT: "LOG_OUT",
};